### ISSUE TITLE
Installation instructions in Readme seem to be outdated / wrong

### ISSUE THREAD

**Issue by bj-rn** [vvvv/VL.QRCode#1]
Just installed VL.QRCode as instructed by the Readme:

`nuget install VL.QRCode -pre`

This installed the following version _VL.QRCode.2020.3.0-0104-g01f9d33628_ instead of [0.0.6-alpha](https://www.nuget.org/packages/VL.QRCode/0.0.6-alpha) which is the latest on nuget.

**Comment by joreg** [comment]
tested this to work correctly now.
